api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: 'API HitMyTeam'
    version: '0.0.1'
    description: 'API du site HitMyTeam'
    show_webby: false
    eager_loading:
        # To enable or disable eager loading.
        enabled: false
